spring:
  profiles:
    active: local
    include:
      - core
management:
  endpoint:
    health:
      enabled: true
    info:
      enabled: false
  health:
    db:
      enabled: false
---
spring:
  profiles: local
management:
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
  health:
    db:
      enabled: true
